### PR TITLE
feat: support transmission 4.00 rpc version 17

### PR DESCRIPTION
**Pull request by trim21**
support new feature in transmission 4.00

BREAKE CHANGE:
fully drop supported for rpc<=14

### CODE REVIEW

**Comment by despian** [comment]
Transmission 4 now has a beta release:

https://github.com/transmission/transmission/releases/tag/4.0.0-beta.1

Will there be a corresponding release of this package? If not what's the best way to get this feature? just pull the branch and do a local merge with master?

**Comment by trim21** [comment]
I haven't try transmission 4.0.0-beta.1 yet, there isn't a release.

I create this branch months ago according to the rpc spec and I'm not very sure that it works with the actual release.

If you want to try you can just install this branch.

**Comment by despian** [comment]
@trim21 it was just released yesterday

**Comment by trim21** [comment]
> Transmission 4 now has a beta release:
> 
> https://github.com/transmission/transmission/releases/tag/4.0.0-beta.1
> 
> Will there be a corresponding release of this package? If not what's the best way to get this feature? just pull the branch and do a local merge with master?

If you want to try you can do this `pip install https://github.com/trim21/transmission-rpc/archive/feature/new-version.zip`

And if you encounter any bug please tell me so I can fix it before merging them to master branch.

**Comment by despian** [comment]
Transmission 4 is officially released now. @trim21 will you be making a corresponding release?

**Comment by trim21** [comment]
> Transmission 4 is officially released now. @trim21 will you be making a corresponding release?

you can use pre-release version

**Pull request merged**
