### PR TITLE
Add additional properties

### PR DESCRIPTION
**Pull request by spacemanspiff2007**

### CODE REVIEW

**Comment by spacemanspiff2007** [comment]
This adds some more properties

**Comment by Trim21** [comment]
are they available for all RPC version? If not, could you add comments in source code about which version they're available.

**Comment by spacemanspiff2007** [comment]
All properties are available for all version except for
 - is_finished from 2.0
 - is_stalled from 2.4

**Comment by spacemanspiff2007** [comment]
Is there something missing from my side that prevents this from getting merged?

**Comment by Trim21** [comment]
Sorry, end of the term, really busy these days.

**Comment by spacemanspiff2007** [comment]
No problem, I'm not in a hurry. I just went over the open PRs of mine to see if something is missing.

**Pull request merged**
