### PR TITLE
Add support for `requests.auth`

### PR DESCRIPTION
**Pull request by labrys**
This adds support for passing requests-compatible auth.  It also uses `requests.auth.HTTPBasicAuth ` if a username and password is passed instead of manually adding basic-auth to the URL.

### CODE REVIEW

**Comment by trim21** [comment]
any use cases that original username and password args can't cover？

**Comment by trim21** [comment]
I don't like this PR because it expose internal implement to users, and in my understanding transmission only support basic auth.

you can pass auth to requests session but please don't add it to constructor's arguments

**Comment by labrys** [comment]
@trim21 As an application, I would agree that exposing implementation details is a bad idea.  However as a library, being open for extension is generally a good thing.  The idea was to deprecate separate username and password fields and instead use the same method as requests does where you can pass either an auth or a username, password tuple.   If you don't like it in the constructor, how would you feel about an alternate constructor that allows for passing both session and auth?

**Comment by trim21** [comment]
But what problem does `requests.auth.AuthBase` solve or what feature does it add and username/password can't do that?

**Comment by labrys** [comment]
There are many ways to get the credentials other than passing them in the constructor.  For example a credentials manager.  Additionally in a long running script a changed password coulr trigger notification or provide methods to reauth.  Those would be out of scope for a library but simple to I implement with an auth handler.  If you don't understand how flexibility is useful for a library I won't be able to explain it to you in GitHub comments.  But that's the beauty of open source, if someone isn't open to contributions you can fork and handle it yourself.  Merry Christmas and I hope you have a great new year.

**Pull request closed without merging**
